---
- hosts: webnodes
  become: yes
  vars:
   telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
  tasks:
    - include_tasks: tasks/apache-installation.yml
    - include_tasks: tasks/wordpress-installation.yml
    - include_tasks: tasks/telegraf-installation.yml
- hosts: private
  become: yes
  vars:
   influx_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
   grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
  tasks:
    - include_tasks: tasks/mysql-installation.yml
    - include_tasks: tasks/mysql-configure.yml
    - name: "install influx"
      yum:
        name: "{{influx_url}}"
        state: present
    - name: "restart influx"
      service:
        name: influxdb
        state: restarted
    - name: "install grafana"
      yum:
        name: "{{grafana_url}}"
        state: present
    - name: "restart grafana"
      service:
        name: grafana-server
        state: restarted
