---
    - name: "Install apache server"
      yum:
            name: httpd
            state: latest
    - name: "install mysql"
      yum:
        name: "{{packages}}"
        state: present
      vars:
        packages:
            - mariadb
            - mariadb-server
    - name: "install php"
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
            - php
            - php-mysql
            - MySQL-python